---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
 name: modresorts-git
spec:
 type: git
 params:
   - name: url
     value: https://github.com/jeremybeucler-ibm/CP4A_lab
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
 name: modresorts-image
spec:
 type: image
 params:
   - name: url
     value: image-registry.openshift-image-registry.svc:5000/kabanero/modresorts:1.0.1
